# Site settings
collections:
  kb:
    output: true
    permalink: /:path/:title/

# Build settings & gem packages
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-last-modified-at
  - jekyll-scholar
  - jekyll-sitemap
  - jekyll-youtube
  - liquid_pluralize
  - liquid_reading_time
  - rouge
exclude:
  - "*.ipynb"
  - "*.py"
  - README.md
  - TODO.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - Makefile
  - package.json
  - node_modules/
  - gulpfile.js
  - requirements.txt
  - learning_bookmarks.txt
  - tags
  - .venv/
  - .ipynb_checkpoints/
  - .DS_Store
# config for https://github.com/inukshuk/jekyll-scholar
scholar:
  bibliography_template: bib
  style: ieee-with-url

# Metadata for plugins like seo-tag and feed
title: John-Gentile
description: Engineering science into reality.
url: https://john-gentile.com
author: John Gentile
logo: /assets/images/Gent-systems_icon_black.png
