# Site settings
collections:
  kb:
    output: true
    permalink: /:path/:title/

# Build settings & gem packages
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-last-modified-at
  #- jekyll-picture-tag
  - jekyll-sitemap
  #- jekyll-seo-tag
  #- jekyll-toc
  - jekyll-youtube
  - liquid_pluralize
  - liquid_reading_time
  - rouge
exclude:
  - README.md
  - TODO.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - Makefile
  - package.json
  - node_modules/
  - gulpfile.js
  - John_Gentile_Resume.docx

# Metadata for plugins like seo-tag and feed
title: John-Gentile
description: Engineering creatively. Learning and development through open-source.
url: https://john-gentile.com
author: John Gentile
logo: /assets/images/Gent-systems_icon_black.png
