name: Build Site and Push to AWS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

        # Cache to shorten build times and decrease load on servers
        # Don't have to install/fetch Gems on every build
#     - uses: actions/cache@v2
#       with:
#         path: vendor/bundle
#         key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
#         restore-keys: |
#           ${{ runner.os }}-gems-

#     - name: Install dependencies
#       run: |
#         sudo apt-get install ruby-full build-essential zlib1g-dev
#         gem install jekyll bundler

      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Jekyll Build
          bundle exec jekyll build

#     - name: Configure AWS Credentials
#       uses: aws-actions/configure-aws-credentials@v1
#       with:
#         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         aws-region: us-east-1

#     - name: Deploy release web files to S3 bucket for static hosting
#       run: aws s3 sync ./dist s3://john-gentile.com --delete

